/**
 * Pure string templates for scripts/scaffold-module.mjs. No file I/O
 * here — every function takes the `names` object (see
 * scaffold-module.mjs's `buildNameVariants`) and returns the exact file
 * contents to write. Kept separate from the CLI script so the
 * templates can be read/edited on their own.
 *
 * Every generated file mirrors an existing, working resource
 * (CxoTeam/BusinessTeam on the backend, cxoTeam on the frontend) —
 * scaffolding a module should never invent a new pattern, only apply
 * the proven one to a new name.
 */

export function backendModelTemplate(n) {
  return `import mongoose from 'mongoose';

import { auditableSchemaPlugin } from './plugins/auditableSchema.plugin.js';

const { Schema } = mongoose;

/**
 * ${n.collectionName} -- TODO: describe what this collection represents
 * and how it relates to other collections (if at all).
 *
 * Generated by scripts/scaffold-module.mjs. Replace the placeholder
 * \`name\` field with this resource's real shape, then update
 * validations/${n.singularCamel}.schema.js to match exactly (the zod
 * schema and this Mongoose schema should always describe the same
 * fields -- see CONTRIBUTING.md's "Database standards").
 */
const ${n.singularCamel}Schema = new Schema(
  {
    name: {
      type: String,
      required: [true, 'Name is required'],
      trim: true,
      maxlength: 150,
    },
    // TODO: add this resource's real fields here.
  },
  { timestamps: true },
);

${n.singularCamel}Schema.plugin(auditableSchemaPlugin, { userRef: 'CxoTeam' });

// Uniqueness scoped to non-deleted documents -- see ARCHITECTURE.md's
// "Data layer" section for why this is a partial index rather than a
// plain \`unique: true\` (it's what makes CSV "replace existing data"
// safe). Remove this index entirely if \`name\` doesn't need to be
// unique for this resource.
${n.singularCamel}Schema.index(
  { name: 1 },
  { unique: true, partialFilterExpression: { isDeleted: { $ne: true } } },
);

// TODO: add indexes for this resource's actual common filter/search
// patterns (see the existing models for examples of compound and text
// indexes).
${n.singularCamel}Schema.index({ name: 'text' });

export default mongoose.model('${n.pascalName}', ${n.singularCamel}Schema, '${n.collectionName}');
`;
}

export function backendRepositoryTemplate(n) {
  return `import { ${n.pascalName} } from '../models/index.js';

import BaseRepository from './BaseRepository.js';

class ${n.pascalName}Repository extends BaseRepository {
  constructor() {
    super(${n.pascalName});
  }

  // TODO: add resource-specific queries here only if BaseRepository's
  // generic findById/findMany/create/updateById/etc. aren't enough
  // (e.g. a lookup by a field other than id). Most modules never need
  // to add anything here.
}

export default ${n.pascalName}Repository;
`;
}

export function backendValidationTemplate(n) {
  return `import { z } from 'zod';

// TODO: replace with this resource's real fields -- keep this in sync
// with models/${n.pascalName}.model.js's schema (see CONTRIBUTING.md's
// "Database standards" for why both layers validate independently).
export const ${n.singularCamel}BodySchema = z.object({
  name: z.string().trim().min(1, 'Name is required').max(150),
});

export const create${n.pascalName}Schema = z.object({ body: ${n.singularCamel}BodySchema });

// Partial: PATCH only validates fields actually present in the payload.
export const update${n.pascalName}Schema = z.object({ body: ${n.singularCamel}BodySchema.partial() });

// No bulkImport schema needed here -- every resource shares
// validations/common/bulkImport.schema.js; per-row validation happens
// inside BaseService.bulkCreate via the bodySchema passed into
// services/${n.pascalName}Service.js.
`;
}

export function backendServiceTemplate(n) {
  return `import ${n.pascalName}Repository from '../repositories/${n.pascalName}Repository.js';
import { ${n.singularCamel}BodySchema } from '../validations/${n.singularCamel}.schema.js';

import BaseService from './BaseService.js';

class ${n.pascalName}Service extends BaseService {
  constructor() {
    super(new ${n.pascalName}Repository(), '${n.pascalName}', {
      // TODO: list every field that must be unique (see
      // CxoTeamService.js for a multi-field example, CxoPermissionService.js
      // for a compound-field example).
      uniqueFields: ['name'],
      bodySchema: ${n.singularCamel}BodySchema,
    });
  }

  // TODO: override list()/getById() only if this resource needs
  // populate() on a reference field (see CxoPermissionService.js), or
  // override create()/update() for side effects beyond plain CRUD.
  // Everything else (pagination, search, bulk import/export/delete,
  // soft delete) is inherited from BaseService with no code here.
}

export default ${n.pascalName}Service;
`;
}

export function backendControllerTemplate(n) {
  return `import ${n.pascalName}Service from '../services/${n.pascalName}Service.js';

import { createCrudController } from './baseController.js';

const ${n.singularCamel}Service = new ${n.pascalName}Service();

// TODO: set this resource's real allowedFilters/searchableFields (the
// query params GET / accepts) -- see cxoTeam.controller.js for an
// example with several filters.
const ${n.singularCamel}Controller = createCrudController(${n.singularCamel}Service, {
  allowedFilters: [],
  searchableFields: ['name'],
});

export default ${n.singularCamel}Controller;
`;
}

export function backendRoutesTemplate(n) {
  return `import { Router } from 'express';

import ${n.singularCamel}Controller from '../../controllers/${n.singularCamel}.controller.js';
import validateRequest from '../../middlewares/validateRequest.js';
import {
  objectIdParamSchema,
  paginationQuerySchema,
  create${n.pascalName}Schema,
  update${n.pascalName}Schema,
  bulkImportSchema,
  bulkDeleteSchema,
} from '../../validations/index.js';

const router = Router();

router.get('/', validateRequest(paginationQuerySchema), ${n.singularCamel}Controller.getAll);
router.post('/import', validateRequest(bulkImportSchema), ${n.singularCamel}Controller.bulkImport);
router.post('/bulk-delete', validateRequest(bulkDeleteSchema), ${n.singularCamel}Controller.bulkRemove);
router.get('/:id', validateRequest(objectIdParamSchema), ${n.singularCamel}Controller.getById);
router.post('/', validateRequest(create${n.pascalName}Schema), ${n.singularCamel}Controller.create);
router.patch(
  '/:id',
  validateRequest(objectIdParamSchema),
  validateRequest(update${n.pascalName}Schema),
  ${n.singularCamel}Controller.update,
);
router.delete('/:id', validateRequest(objectIdParamSchema), ${n.singularCamel}Controller.remove);

export default router;
`;
}

export function frontendApiServiceTemplate(n) {
  return `import ApiService from '../baseApiService.js';

class ${n.pascalName}ApiService extends ApiService {
  constructor() {
    super('/v1/${n.routeSegment}');
  }
}

export default new ${n.pascalName}ApiService();
`;
}

export function frontendManagementConfigTemplate(n) {
  const S = n.screamingSnake;
  return `/** TODO: table columns for the ${n.pluralPascal} management page. */
export const ${S}_COLUMNS = [{ key: 'name', header: 'Name' }];

// TODO: add filter dropdowns here if this resource has enum-like
// fields (see features/cxoTeams/cxoTeam.management.config.js's status
// filter for an example). Leave empty and rely on search otherwise.
export const ${S}_FILTERS = [];

/** Create/edit form + view modal field definitions, shared by both. */
export const ${S}_FIELDS = [
  { name: 'name', label: 'Name', type: 'text', required: true },
  // TODO: add the rest of this resource's fields.
];

export const ${S}_EMPTY_VALUES = {
  name: '',
};

const ${S}_EXPORT_FIELDS = [{ header: 'Name', key: 'name' }];

/** Maps one parsed CSV row (raw string columns) into a create payload. */
function mapImportRow(raw) {
  return {
    name: raw.Name,
  };
}

// Shown as the one example row in the downloadable import template.
const ${S}_TEMPLATE_SAMPLE_ROW = {
  name: 'Example name',
};

export const ${S}_CSV_CONFIG = {
  exportFields: ${S}_EXPORT_FIELDS,
  filenamePrefix: '${n.routeSegment}',
  mapImportRow,
  templateSampleRow: ${S}_TEMPLATE_SAMPLE_ROW,
};
`;
}

export function frontendPageTemplate(n) {
  const S = n.screamingSnake;
  return `import ManagementPage from '../components/management/ManagementPage.jsx';
import ${n.singularCamel}ApiService from '../api/services/${n.singularCamel}ApiService.js';
import {
  ${S}_COLUMNS,
  ${S}_FILTERS,
  ${S}_FIELDS,
  ${S}_EMPTY_VALUES,
  ${S}_CSV_CONFIG,
} from '../features/${n.pluralCamel}/${n.singularCamel}.management.config.js';

const config = {
  apiService: ${n.singularCamel}ApiService,
  resourceLabel: '${n.pascalName}',
  emptyValues: ${S}_EMPTY_VALUES,
  fields: ${S}_FIELDS,
  csv: ${S}_CSV_CONFIG,
  getRowLabel: (row) => row?.name,
};

// TODO: replace the description below with a one-line summary of this
// module.
export default function ${n.pluralPascal}Page() {
  return (
    <ManagementPage
      title="${n.pluralPascal}"
      description="TODO: describe this module."
      columns={${S}_COLUMNS}
      filters={${S}_FILTERS}
      config={config}
    />
  );
}
`;
}
